export const SET_USER_INFO = 'SET_USER_INFO'

export const SET_HEADER_SEARCH_STR = 'SET_HEADER_SEARCH_STR'
export const SET_HEADER_MORE_POPUP = 'SET_HEADER_MORE_POPUP'
export const TOGGLE_HEADER_MORE_POPUP = 'TOGGLE_HEADER_MORE_POPUP'

export const SET_NEWEST_MEETING_LIST = 'SET_NEWEST_MEETING_LIST'
export const SET_MY_COLLLECTION_LIST = 'SET_MY_COLLLECTION_LIST'
export const BOOK_MARK_MY_COLLOCTION = 'BOOK_MARK_MY_COLLOCTION'
export const SET_HISTORY_MEETING_LIST = 'SET_HISTORY_MEETING_LIST'
export const SET_PUBLISHED_MEETING_LIST = 'SET_PUBLISHED_MEETING_LIST'
export const SET_LATESTPLAY_MEETING_LIST = 'SET_LATESTPLAY_MEETING_LIST'

export const SET_MEETING_DETAIL = 'SET_MEETING_DETAIL'
export const SET_COMMENT_LIST = 'SET_COMMENT_LIST'

export const CLEAR_ATTENDANCE_LIST = 'CLEAR_ATTENDANCE_LIST'
export const ADD_ATTENDANCE_TO_LIST = 'ADD_ATTENDANCE_TO_LIST'
export const REMOVE_ATTENDANCE_FROM_LIST = 'REMOVE_ATTENDANCE_FROM_LIST'

export const SET_IWIND_CONTACT_LIST = 'SET_IWIND_CONTACT_LIST'
export const MERGE_IWIND_CONTACT_LIST = 'MERGE_IWIND_CONTACT_LIST'
export const SET_PHONE_CONTACT_LIST = 'SET_PHONE_CONTACT_LIST'

export const SET_MEETINGINFO_LIST = 'SET_MEETINGINFO_LIST'
export const SET_PRIVATE_MEETING_LIST = 'SET_PRIVATE_MEETING_LIST'
export const SET_SERVERINFO = 'SET_SERVERINFO'
export const SET_CURRENT_PLAY_MEETING = 'SET_CURRENT_PLAY_MEETING'
export const SET_PERSONAL_CENTER_COUNT = 'SET_PERSONAL_CENTER_COUNT'
export const SET_RESTRICTED_MEETING_LIST = 'SET_RESTRICTED_MEETING_LIST'
export const SET_SESSIONID = 'SET_SESSIONID'
export const SET_APP_INFO = 'SET_APP_INFO'
